
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'intro',
    'why-detian',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation-and-running',
        'getting-started/mental-model',
        'getting-started/first-program',
        'getting-started/package-roots-and-lockfiles',
      ],
    },
    {
      type: 'category',
      label: 'Language',
      items: [
        'language/language-overview',
        'language/execution-model',
        'language/at-sign-and-execution-start',
        'language/groups-threads-and-main',
        'language/flows-pipes-and-run-handles',
        'language/types-and-data',
        'language/records-maps-json-and-bytes',
        'language/expressions-operators-and-control',
        'language/collections-and-comprehensions',
        'language/advanced-lists-and-sequences',
        'language/error-result-and-diagnostics',
        'language/stdlib-builtin-and-hya',
        'language/modules-and-capabilities',
        'language/language-reference',
        'language/nullability-and-autoflow',
      ],
    },
    {
      type: 'category',
      label: 'Hya & HYX',
      items: [
        'hya/hya-overview',
        'hya/request-lifecycle',
        'hya/components-state-actions',
        'hya/forms-actions-and-state',
        'hya/routing',
        'hya/hyx-guide',
        'hya/fine-grained-authoring',
        'hya/fine-grained-reactivity',
        'hya/fine-grained-reactivity-plan',
        {
          type: 'category',
          label: 'Tutorial Series',
          items: [
            'hya/tutorials/overview',
            'hya/tutorials/project-setup-and-first-route',
            'hya/tutorials/counter-foundations',
            'hya/tutorials/pages-routes-and-layout',
            'hya/tutorials/components-and-composition',
            'hya/tutorials/actions-and-reducers',
            'hya/tutorials/forms-inputs-and-submit-flows',
            'hya/tutorials/dynamic-routes-and-detail-pages',
            'hya/tutorials/static-assets-and-json-endpoints',
            'hya/tutorials/fine-grained-rendering',
            'hya/tutorials/optimistic-actions-and-reconcile',
            'hya/tutorials/debugging-hya-apps',
            'hya/tutorials/capstone-launchpad-crm',
          ],
        },
        {
          type: 'category',
          label: 'Milestones',
          items: [
            'hya/milestones/overview',
            'hya/milestones/milestone-a',
            'hya/milestones/milestone-b',
            'hya/milestones/milestone-c',
            'hya/milestones/milestone-d',
            'hya/milestones/milestone-d2',
            'hya/milestones/milestone-d4',
            'hya/milestones/milestone-e',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/tutorial',
        'guides/build-a-small-hya-app',
        'guides/package-authoring',
        'guides/common-language-patterns',
        'guides/examples-and-patterns',
      ],
    },
    {
      type: 'category',
      label: 'Tooling',
      items: [
        'tooling/lsp',
        'tooling/cli-and-package-commands',
        'tooling/testing-and-regression',
        'tooling/error-messages',
        'tooling/diagnostics-and-editor-workflows',
        'tooling/traces-and-flowviz',
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      items: [
        'packages/overview',
        'packages/package-catalog',
        'packages/framework-and-web',
        'packages/data-and-storage',
        'packages/ai-visualization-and-graphs',
        'packages/math-stats-and-science',
        'packages/security-auth-and-ops',
        {
          type: 'category',
          label: 'Cookbooks',
          items: [
            'packages/cookbooks/hya-counter',
            'packages/cookbooks/hya-routing-and-params',
            'packages/cookbooks/llmx-chat-tools-embeddings',
            'packages/cookbooks/db-and-migrations',
            'packages/cookbooks/regex-and-text-processing',
            'packages/cookbooks/flowviz-and-run-graphs',
            'packages/cookbooks/chart-and-render-pipeline',
            'packages/cookbooks/internal-tool-stack',
          ],
        },
        'packages/aix',
        'packages/ezml',
        'packages/authx',
        'packages/builtin',
        'packages/cachex',
        'packages/chart',
        'packages/clix',
        'packages/crypto',
        'packages/datetime',
        'packages/db',
        'packages/filex',
        'packages/flowviz',
        'packages/graph',
        'packages/httpx',
        'packages/hya',
        'packages/imgx',
        'packages/jsonx',
        'packages/llmx',
        'packages/mathx',
        'packages/ndx',
        'packages/metricsx',
        'packages/queuex',
        'packages/regex',
        'packages/renderx',
        'packages/sciencex',
        'packages/statsx',
        'packages/svgx',
        'packages/tabular',
        'packages/testx',
        'packages/uuidx',
        'packages/visionx',
        'packages/webkit',

      ],
    },
    {
      type: 'category',
      label: 'Internals',
      items: [
        'internals/architecture',
        'internals/runtime-architecture-deep-dive',
        'internals/roadmap',
      ],
    },
  ],
};

export default sidebars;
